version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: ls -ltra
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            cd app && pipenv run python manage.py test && flake8
